#ifndef _FPGA_REGS_H_
#define _FPGA_REGS_H_


#define PRINTER_DATA_MASTER_READ_CONTROL_READ_EN 0
#define PRINTER_DATA_MASTER_READ_CONTROL_READ_BLOCK_SIZE 1
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_BASE_PH0 2
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_SEED_PH0 3
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_BASE_PH1 4
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_SEED_PH1 5
#define PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_EN 6
#define PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_BLOCK_SIZE 7
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_BASE_PH0 8
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_SEED_PH0 9
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_BASE_PH1 10

#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_SEED_PH1 11
#define PRINTER_DATA_MASTER_READ_CONTROL_DONE_CNT_PH0 12
#define PRINTER_DATA_MASTER_READ_CONTROL_EARLY_DONE_CNT_PH0 13
#define	PRINTER_DATA_MASTER_READ_CHECK_ERR_CNT_PH0 14
#define	PRINTER_DATA_MASTER_READ_CONTROL_IRQ_CNT_PH0 15
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_IRQ_CNT_PH0 16
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_DONE_CNT_PH0 17
#define PRINTER_DATA_MASTER_WRITE_DATA_ERR_CNT_PH0 18
#define PRINTER_DATA_MASTER_READ_CONTROL_DONE_CNT_PH1 19
#define PRINTER_DATA_MASTER_READ_CONTROL_EARLY_DONE_CNT_PH1 20

#define	PRINTER_DATA_MASTER_READ_CHECK_ERR_CNT_PH1 21
#define	PRINTER_DATA_MASTER_READ_CONTROL_IRQ_CNT_PH1 22
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_IRQ_CNT_PH1 23
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_DONE_CNT_PH1 24
#define	PRINTER_DATA_MASTER_WRITE_DATA_ERR_CNT_PH1 25
#define	PRINTER_DATA_MASTER_READ_CLEAN_PH0_PH1 26
#define	PRINTER_DATA_MASTER_WRITE_CLEAN_PH0_PH1 27
#define	I_PLL_PHCLK_LOCKED_FPGA_CLK_100_LOCK 28
#define	LOCAL_INIT_DONE_LOCAL_CAL_SUCCESS_LOCAL_CAL_FAIL 29
#define	WRITE_BEGIN 30

#define	READ_BEGIN 31
#define	PRBS_SEED 32
#define	READ_CHECK_ERR_INDEX 33
#define	READ_CHECK_ERR_CNT 34
#define	READ_CHECK_ERR_CLEAN 35
#define	PRBS_EN 36
#define PRINT_OPEN 37
#define	DMA_RAM_WRITE_DONE_BLOCK_CNT_PH0 38
#define	DMA_RAM_WRITE_DONE_BLOCK_CNT_PH1 39
#define	DMA_RAM_READ_DONE_BLOCK_CNT 40
#define	O_MASTER_INDICATOR 50
#define	O_MASTER_ID 51
#define O_MASTER_DPI_D_FACTOR 60
#define O_MASTER_DPI_M_FACTOR 61
#define O_MASTER_DPI_T_FACTOR 62
#define O_MASTER_DPI_FIFO_THRESHOLD 63

#define MASTER_SYNC_SIM_EN 70
#define O_MASTER_RASTER_SEL	71
#define	O_MASTER_RASTER_SIM_PERIOD 72
#define O_MASTER_PD_SEL 73
#define O_MASTER_PD_REVERSE 74
#define	O_MASTER_PD_SIM_NUMBER 75
#define	O_MASTER_PD_SIM_LENGTH 76
#define	O_MASTER_PD_SIM_INTERVAL 77

#define	I_MASTER_RASTERA_CNT_I_MASTER_RASTERB_CNT 80
#define	I_MASTER_RASTER_ANTI_CNT 81
#define	I_MASTER_RASTER_POSX 82
#define	I_MASTER_DPI_POSX 84


#define	O_ID_UPDATE_EN 100
#define	I_ID_UPDATE_CNT 101
#define	I_TX_ID_I_RX_ID_I_BOARD_ID 102
#define	I_RX_STA 103
#define	I_RX_ALT_CNT 104

#define	O_CNT_CLR 110
#define	I_DPI_POSX_RX 111

#define	O_WORK_MODE 120
#define	O_PRINT_DIRECTION 121 
#define	O_INK_DROPLET_MODE 122
#define	O_JOB_FIRE_NUM 123
#define	O_DDR_BUFF_DEEP 124

#define	O_BASE_IMAGE_EN 130
#define	I_BASE_IMAGE_TRANFER_COMPLETE 131
#define	I_BASE_IMAGE_WRITE_OVER_CNT 132

#define	O_PH_OFFSET 150
#define	O_CH_OFFSET_0_31 151
#define	O_CH_OFFSET_32_63 152
#define	O_CH_OFFSET_64_95 153
#define	O_CH_OFFSET_96_127 154
#define	O_CH_OFFSET_128_159 155
#define	O_CH_OFFSET_160_191 156
#define	O_CH_OFFSET_192_223 157
#define	O_CH_OFFSET_224_255 158


#define	O_DPI_DELAY_NUM_PH0 170
#define	O_SUB_DELAY_NUM_PH0 171
#define	O_DPI_DELAY_NUM_PH1 172
#define	O_SUB_DELAY_NUM_PH1 173

#define	O_SW_INIT_EN 180
#define	O_SW_RW_CPU 181
#define	O_SW_ADDR_CPU 182
#define	O_SW_WDATA_CPU 183 
#define	I_SW_RDATA0_CPU 184
#define	I_SW_RDATA1_CPU 185

#define	O_PD_CHK_THRESHOLD 200
#define	I_PD_IN_OK_CNT 201
#define	I_PD_IN_ERR_CNT 202
#define	I_PD_IN_CNT 203
#define	I_PD_IN_MIN 204
#define	I_PD_IN_MAX 205


#define	O_PD_SERACH_MODE 210
#define	O_PD_SEARCH_INTERVAL 211
#define	O_PD_SEARCH_WINDOW 212
#define	O_PD_VIRTUAL_EN 213
#define	I_PD_LOSS_ERR_CNT 214
#define	I_PD_REQ_CNT 215

#define	O_INK_DROPLET_MODE_PROTECT 220
#define	O_PROTECT_FIRE_EN 221
#define	O_PROTECT_FIRE_LIMIT_SET 222
#define	O_PROTECT_FIRE_NUMBER_SET 222
#define	I_PROTECT_FIRE_NUMBER 224
#define	I_PROTECT_FIRE_EN_INDEX 225

#define	O_TEST_DATA_EN 240
#define	O_LOOP_TEST_EN 241
#define	I_LOOP_WR_OVER_CNT 242
#define	I_LOOP_RD_OVER_CNT_PH0 243
#define	I_LOOP_RD_OVER_CNT_PH1 244

#define	I_REAL_FIRE_REQ_CNT 260
#define	I_FIRE_CNT_PH0 262
#define	I_FIRE_CNT_PH1 264

#define	I_FIRE_REQ_CNT 270
#define	I_JOB_COMPLETE_CNT 272
#define	I_DDR_WR_REQ_DONE_CNT_TOTAL 274
#define	I_DDR_RD_REQ_DONE_CNT_TOTAL 276
#define	I_PRINT_START_POSX_ALL 278
#define	I_PRINT_END_POSX_ALL 280

#define	I_WR_CAHCE_FULL_I_WR_CACHE_EMPTY 290
#define	I_DDR_FULL_I_DDR_EMPTY 291
#define	I_RAM_FULL_I_RAM_EMPTY 292
#define	I_PRINT_EMPTY_EVENT 293

#define I_PRINT_ERR_EVENT 300
#define I_DDR_RD_EMPTY_ERR_EVENT_I_DDR_RD_OVERCLOCK_ERR_EVENT 301
#define	I_RAM_RD_EMPTY_EVENT_I_RAM_WR_FULL_EVENT 302
#define I_PRINT_END_POSX_ERR_EVENT_I_PRINT_START_POSX_ERR_EVENT 303
#define I_FIRE_OVERCLOCK_ERR_EVENT 304
#define	I_TEST_DATA_ERR_EVENT 305
#define	I_LOOP_WR_FULL_ERR_EVENT 306

#define I_ALARM_EVENT 310
#define O_ALARM_EVENT_CLR 311
#define	ALARM_IRQ_MASK 312
#define I_LOOP_TEST_COMPLETE_PH1_I_LOOP_TEST_COMPLETE_PH0_I_PRINT_COMPLETE 320
#define I_PH1_TEMP_I_PH0_TEMP 330
#define	I_TEMP_ERR_CNT_PH1_I_TEMP_ERR_CNT_PH0 331

#define O_EN_UV2_O_EN_UV1 340
#define O_PH0_DSEL2_O_PH0_DSEL1 341
#define	O_PH1_DSEL2_O_PH1_DSEL1 342
#define O_GPO_01 343 
#define O_GPO_02 344
#define	O_GPO_03 345
#define	I_GPI_02_I_GPI_01 346

#define CPU_TEST 509
#define	FPGA_TYPE 510
#define	FPGA_DATE 511

#endif


