/* fpga regs about dma */
#define PRINTER_DATA_MASTER_READ_CONTROL_READ_EN 0
#define PRINTER_DATA_MASTER_READ_CONTROL_READ_BLOCK_SIZE 1
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_BASE_PH0 2
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_SEED_PH0 3
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_BASE_PH1 4
#define	PRINTER_DATA_MASTER_READ_CONTROL_READ_SEED_PH1 5
#define PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_EN 6
#define PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_BLOCK_SIZE 7
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_BASE_PH0 8
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_SEED_PH0 9
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_BASE_PH1 10
#define	PRINTER_DATA_MASTER_WRITE_CONTROL_WRITE_SEED_PH1 11
#define PRINTER_DATA_MASTER_READ_CLEAN 26
#define PRINTER_DATA_MASTER_WRITE_CLEAN 27
#define I_PLL_PHCLK_LOCKED_FPGA_CLK_100_LOCK 28
#define LOCAL_INIT_DONE_LOCAL_CAL_SUCCESS_LOCAL_CAL_FAIL 29
#define WRITE_BEGIN 30
#define READ_BEGIN 31
#define PRBS_SEED 32
#define READ_CHECK_ERR_INDEX 33
#define READ_CHECK_ERR_CNT 34
#define READ_CHECK_ERR_CLEAN 35
#define PRBS_EN 36
#define DMA_RAM_WRITE_DONE_BLOCK_CNT_PH0 38
#define DMA_RAM_WRITE_DONE_BLOCK_CNT_PH1 39
#define DMA_RAM_READ_DONE_BLOCK_CNT 40



/* fpga regs about print */
#define PRINT_OPEN 37
#define MASTER_SYNC_SIM_EN 52
#define O_MASTER_DPI_D_FACTOR 53
#define O_MASTER_DPI_M_FACTOR 54
#define O_MASTER_DPI_T_FACTOR 55
#define O_MASTER_RASTER_SEL	60
#define	O_MASTER_RASTER_SIM_PERIOD 62
#define O_MASTER_PD_SEL 70
#define	O_MASTER_PD_SIM_NUMBER 73
#define	O_MASTER_PD_SIM_LENGTH 74
#define	O_MASTER_PD_SIM_INTERVAL 75
#define	O_PD_CHK_THRESHOLD 80
#define	O_PD_SERACH_MODE 90
#define	O_PD_SEARCH_INTERVAL 91
#define	O_PD_SEARCH_WINDOW 92
#define	O_PD_VIRTUAL_EN 93
#define O_DDR_BUFF_DEEP 100
#define O_WORK_MODE	110
#define O_JOB_FIRE_NUM 113
#define O_BASE_IMAGE_EN 114
#define I_BASE_IMAGE_TRANFER_COMPLETE 115
#define	O_TEST_DATA_EN 140
#define	O_LOOP_TEST_EN 145
#define	O_SW_INIT_EN 150

